### ISSUE TITLE
Python 2.6 support

### ISSUE THREAD

**Issue by kalxas** [PublicaMundi/ckanext-publicamundi#95]
https://github.com/PublicaMundi/ckanext-publicamundi/blob/master/ckanext/publicamundi/plugins.py#L114-L115

This syntax is not supported in Python 2.6, breaking installation on Redhat based systems.

**Comment by kalxas** [comment]
Also 
https://github.com/PublicaMundi/ckanext-publicamundi/blob/master/vectorstorer-requirements.txt#L3
is not supporting Python 2.6

**Comment by kalxas** [comment]
File "/var/local/ckan/default/pyenv/src/ckanext-publicamundi/ckanext/publicamundi/lib/metadata/validators.py", line 6, in <module>
    from collections import Counter
ImportError: cannot import name Counter

**Comment by kalxas** [comment]
Possible solution:
http://code.activestate.com/recipes/576611-counter-class/

**Comment by kalxas** [comment]
Possible solution:
https://github.com/mne-tools/mne-python/commit/4743326415ad8f53dc06c7ede8f85ba42c5ea3dd
https://github.com/dengemann/mne-python/blob/master/mne/fixes.py#L54

**Comment by drmalex07** [comment]
@kalxas  As you have already figured-out this is due to the new feature of "dict comprehension" introduced as PEP274 at Python 2.7 (https://www.python.org/dev/peps/pep-0274/). This language feature is supposed to be provide a faster shortcut over the conventional way of forming pairs and then converting them to a dict.

Anyway, as we have been using this feature heavily, i think the proper way to handle this issue is to maintain a separate branch supporting Python 2.6.

I will tag this as an enhancement.

**Comment by kalxas** [comment]
Since we don't plan to move away from this Python 2.7 feature, this issue is closed.
